### ISSUE TITLE
Domain Search Form on Mobile

### ISSUE THREAD

**Issue by tobsowo** [getpinga/Tide#15]
The domain name, tld and search button are on a single row on mobile making the text area very small.
![IMG_20230704_151849.jpg](https://github.com/getpinga/Tide/assets/5642737/5e360585-2783-4bb9-a407-df97c92e3135)

**Comment by getpinga** [comment]
It is already fixed, will be available as version 0.9.3 soon.

**Comment by getpinga** [comment]
Fixed
