### ISSUE TITLE
Profile screen needs to display an alert when emails aren't verified

### ISSUE THREAD

**Issue by BelleNottelling** [getpinga/tide#28]
When FOSSBilling version 0.5.5 comes out, the email verification system will be fixed / improved.
Namely: Accounts with unverified email addresses will still be allowed to login, but they will only be permitted to visit their profile, update their info, and request that the verification email is resent.

To account for this, the profile page needs to be updated to:
1. Show an alert when email verification is required and their email is unverified.
2. Provide a "resend verification email" button.
![image](https://github.com/getpinga/Tide/assets/17304943/4fc09aa0-afe7-46f7-91c9-9e4fcfc63435)

The change required for this is quite minimal:
https://github.com/FOSSBilling/FOSSBilling/pull/1451/files#diff-653ec101584c3dedf182956aa6d856b4d918740124cfef7dd389fcd142f16adf

**Comment by getpinga** [comment]
Thanks, implemented the fix.
