### ISSUE TITLE
Move login before check out for guest

### ISSUE THREAD

**Issue by tobsowo** [getpinga/tide#32]
When a guest wants to checkout, they are required to login or register but that is below which can be confusing. Bring the login box before the checkout button will improve on experience.

**Comment by abusayed0206** [comment]
I also faced this problem! To temporarily fix this issue i had to disable "Dashboard for guest"!

I hope, author will make the login/register option before "Checkout"

**Comment by getpinga** [comment]
Thanks a lot, this has been now fixed. Please test.

**Comment by tobsowo** [comment]
Thank you, I'll check.
