### ISSUE TITLE
Set new password

### ISSUE THREAD

**Issue by insxa** [getpinga/tide#33]
On billing.domain.com/client/reset-password-confirm/
After client reset password and clicked link there is no HTML/CSS style page, its blank
![Snimka zaslona (27)](https://github.com/getpinga/tide/assets/19369515/69a570a3-f8d3-4168-a31b-5f99737fcc81)

**Comment by gilesytheking** [comment]
Yep, I have noticed this too.

**Comment by BelleNottelling** [comment]
It's missing the set new password template that was added in 0.5.6:
https://github.com/FOSSBilling/FOSSBilling/blob/main/src/modules/Client/html_client/mod_client_set_new_password.html.twig
