### ISSUE TITLE
Constant "BB_URL" is undefined.

### ISSUE THREAD

**Issue by gilesytheking** [getpinga/tide#37]
I'm getting the following error on the client dashboard with the latest Preview Build of Foss (downloaded 13/11/2023).

Constant "BB_URL" is undefined.

This is on my Staging site of FOSS billing. Not sure what has been updated within FOSS core but it is now causing Tide theme now to work. Can't navigate to any pages on the client side when Tide is enabled.

**Comment by getpinga** [comment]
Thanks a lot, the PR has been now merged.
