### ISSUE TITLE
Upcoming changes with FOSSBilling

### ISSUE THREAD

**Issue by BelleNottelling** [getpinga/tide#38]
Hi, @getpinga I hope you are doing well.
I wanted to let you know that if all goes to plan we intend to be publishing FOSSBilling version 0.6.0 about 1 week after PHP 8.3 reaches GA (should be a few weeks from now).
With this release, some backwards incompatible changes will be coming out which will effect the Tide theme.
There are also some new features which might be nice to Tide to support, however they aren't needed for compatibility.
The fully up-to-date changes are here:
https://fossbilling.org/docs/changelog#060-wip

In your case, I believe the only thing that will be necessary to get things working once again is replace references to `BB_URL` with `SYSTEM_URL`, however I have not investigated.

**Comment by BelleNottelling** [comment]
Having done further work to catch-up our own theme work from ~4 month ago, there's a bit more required to fully migrate it.

At the absolute minimum the constant needs to be updated, however there's still changes needed to reflect newly added features. Additionally, there are changes required to reflect the fact that the KB and support modules got merged and without it the KB will be unusable with Tide.

There is also the new password reset template that was originally introduced with 0.5.6, however our base templates are now all using Bootstrap 5 so it's entirely likely that template would still look fine once loaded inside of this theme (Tabler is built on Bootstrap 5 so they should be *mostly* interchangeable without too much headache)

**Comment by gilesytheking** [comment]
@evilmc I have patched the BB_URL issue which gets the template working again with V6, but that's all. There are still some items that need to be worked on to bring tide up to date with the latest changes made in Foss.

You can download the patched version from my fork here - https://github.com/gilesytheking/tide

Hope that helps.

**Comment by getpinga** [comment]
Thanks a lot everyone, the PR has been merged with the main branch too.
Will test now with the last FOSSBilling and make any further changes if needed.

**Comment by BelleNottelling** [comment]
FYI @getpinga this is still incomplete as neither of the merged PRs accounted for the fact that the the KB and support modules were merged

**Comment by evilmc** [comment]
Latest update have 404 error when I click on `https://domain.com/signup`

**Comment by getpinga** [comment]
> FYI @getpinga this is still incomplete as neither of the merged PRs accounted for the fact that the the KB and support modules were merged

Thanks a lot. Now it seems to have it fixed.

**Comment by getpinga** [comment]
> Latest update have 404 error when I click on `https://domain.com/signup`

Thanks, the latest merged PRs fixed this.
